use_frameworks!

platform :ios, '9.0'

target 'AxxlNetworking_Example' do
  pod 'AxxlNetworking', :path => '../'

  target 'AxxlNetworking_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
